version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: # SET USER
      POSTGRES_PASSWORD: # SET PASSWORD
      POSTGRES_DB: # SET DB
  adm:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      # - ./pgadmin:/var/lib/pgadmin/storage 
    ports:
      - "8888:80"
      - "443:443"
    environment:
       PGADMIN_DEFAULT_EMAIL: # SET MAIL ADDRESS
       PGADMIN_DEFAULT_PASSWORD: # SET PASSWORD

